# configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default
data: #key: default.conf
  default.conf: |
    server {
       index index.php index.html;
       error_log  /var/log/nginx/error.log;
       access_log /var/log/nginx/access.log;
       root /code;

       location / {
           try_files $uri $uri/ /index.php?$query_string;
       }

       location ~ \.php$ {
           try_files $uri =404;
           fastcgi_split_path_info ^(.+\.php)(/.+)$;
           fastcgi_pass 127.0.0.1:9000;
           fastcgi_index index.php;
           include fastcgi_params;
           fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
           fastcgi_param PATH_INFO $fastcgi_path_info;
         }
     }

# nginx-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  # manage the pods that are created by the deployment
  selector:
    matchLabels:
      app: nginx-deployment
  # define manifest for the pod
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-default-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: code
          mountPath: /code # thư mục mà mình map trong container
          subPath: code
      - name: php
        image: php:7-fpm
        volumeMounts:
        - name: code
          mountPath: /code # thư mục mà mình map trong container
          subPath: code
        ports:
        - containerPort: 9000
      volumes:
      - name: nginx-default-conf
        configMap:
          name: nginx-default #configmap name
          items:
          - key: default.conf #key mà mình định nghĩa trong configmap
            path: default.conf #tức nghĩa là nó sẽ tạo ra 1 cái file là default.conf lưu ý là file này mình chỉ edit được thông qua kubectl edit configmap nhé
      - name: code
        hostPath:
          path: /code
          type: DirectoryOrCreate #nếu thư mục này không tồn tại thì nó sẽ tạo ra thư mục mới, nếu tồn tại rồi thì nó sẽ mount vào thư mục đó

# service nginx 
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-deployment
  ports:
  - name: nginx
    port: 80 #service port  
    targetPort: 80 #POD port
    nodePort: 30100 #Node 


