apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    app: service-pod #label của các pod tương ứng
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: service-lb
spec:
  selector:
    app: service-pod #label của các pod tương ứng
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000

