apiVersion: v1
kind: Pod
metadata:
  name: react-app
  labels:
    app: react-pod
spec:
  containers:
    - name: my-react-app
      image: maiconghau/my-app-docker
      ports:
        - containerPort: 3000 #POD của container reacta-app
---
apiVersion: v1
kind: Service
metadata:
  name: service-react-app
spec:
  type: NodePort 
  selector:
    app: react-pod # Tên labels của pod tương ứng
  ports:
    - name: react
      port: 3000 #port của service  
      targetPort: 3000 #port của pod -> container
      nodePort: 30000 #Port của node
