# configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default
data: #key: default.conf
  default.conf: |
    server {
       index index.php index.html;
       error_log  /var/log/nginx/error.log;
       access_log /var/log/nginx/access.log;
       root /var/www/html/public;

       location / {
           try_files $uri $uri/ /index.php?$query_string;
       }

       location ~ \.php$ {
           try_files $uri =404;
           fastcgi_split_path_info ^(.+\.php)(/.+)$;
           fastcgi_pass 127.0.0.1:9000;
           fastcgi_index index.php;
           include fastcgi_params;
           fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
           fastcgi_param PATH_INFO $fastcgi_path_info;
         }
     }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-env
data:
  .env: |
    APP_NAME=Laravel
    APP_ENV=local
    APP_KEY=base64:MDfM2j3n66UQ5wqCZQBH6Cix0OFdHkpW2wgXf4lnW4I=
    APP_DEBUG=true
    LOG_CHANNEL=stack

    DB_CONNECTION=mysql
    DB_HOST=mysql
    DB_PORT=3306
    DB_DATABASE=test
    DB_USERNAME=root
    DB_PASSWORD=test123

    BROADCAST_DRIVER=pusher
    CACHE_DRIVER=file
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=redis
    SESSION_LIFETIME=120

    REDIS_HOST=127.0.0.1
    REDIS_PASSWORD=null
    REDIS_PORT=6379
    REDIS_CLIENT=predis

    MAIL_DRIVER=smtp
    MAIL_HOST=10.11.15.24:1025
    MAIL_PORT=8025
    MAIL_USERNAME=null
    MAIL_PASSWORD=null
    MAIL_ENCRYPTION=null
    # MAIL_FROM_ADDRESS = 'pressTest@tohogakuen.ac.jp'
    MAIL_FROM_NAME ="${APP_NAME}"

    PUSHER_APP_ID=anyID
    PUSHER_APP_KEY=anyKey
    PUSHER_APP_SECRET=anySecretID
    PUSHER_APP_CLUSTER=mt1

    MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
    MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-laravel
spec:
  replicas: 1
  # manage the pods that are created by the deployment
  selector:
    matchLabels:
      app: nginx-laravel
  # define manifest for the pod
  template:
    metadata:
      labels:
        app: nginx-laravel
    # Important! After this container has started, the PHP files
    #s  in our Docker image aren't in the shared volume. 
    # If we tried to write directly to this volume from our Docker image
    #  the files wouldn't appear in the nginx container.
    # So, after the container hastarted, copy the PHP files from this
    # container's local filesystem
    spec:
      containers:
      - name: php
        image: maiconghau/laravel-docker:latest
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: shared-data
          mountPath: /code
        - name: laravel-env-config
          mountPath: /var/www/html/.env
          subPath: .env
        workingDir: /
        lifecycle:
          postStart:
            exec:
              command:
              - "sh"
              - "-c"
              - >
                cp -a /var/www/html/. /code &&  cd ./var/www/html  && composer require predis/predis && php artisan optimize:clear  && php artisan config:clear  && php artisan cache:clear  && php artisan view:clear && chmod o+w ./storage/ -R && redis-server --daemonize yes
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-data
          mountPath: /var/www/html
        - name: nginx-default-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      # communicate between php and nginx
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: nginx-default-conf
        configMap:
          name: nginx-default #configmap name
          items:
          - key: default.conf #key mà mình định nghĩa trong configmap
            path: default.conf #tức nghĩa là nó sẽ tạo ra 1 cái file là default.conf lưu ý là file này mình chỉ edit được thông qua kubectl edit configmap nhé
      - name: laravel-env-config
        configMap:
          name: laravel-env
          items:
          - key: .env
            path: .env
# service nginx 
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-laravel
  ports:
  - protocol: TCP
    port: 80 #service port  
    targetPort: 80 #POD port
    nodePort: 30000 #Node 

